// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASfgrFkYB0fr1nT28fPEBJ3fD01Cxc8L0',
    appId: '1:796483662542:web:64411b8094a3cb1e35169f',
    messagingSenderId: '796483662542',
    projectId: 'traffix-app-ac817',
    authDomain: 'traffix-app-ac817.firebaseapp.com',
    storageBucket: 'traffix-app-ac817.firebasestorage.app',
    measurementId: 'G-9J9FR5W7MD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWWBDZmKtgo0-iHRWb920TAIAFMuAVaXI',
    appId: '1:796483662542:android:39e71b96809b484535169f',
    messagingSenderId: '796483662542',
    projectId: 'traffix-app-ac817',
    storageBucket: 'traffix-app-ac817.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvbxYssQkdfu2aMR-VXXvDPgwHb7DphII',
    appId: '1:796483662542:ios:ca26a0be58fbb6a635169f',
    messagingSenderId: '796483662542',
    projectId: 'traffix-app-ac817',
    storageBucket: 'traffix-app-ac817.firebasestorage.app',
    iosBundleId: 'com.example.traffix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvbxYssQkdfu2aMR-VXXvDPgwHb7DphII',
    appId: '1:796483662542:ios:ca26a0be58fbb6a635169f',
    messagingSenderId: '796483662542',
    projectId: 'traffix-app-ac817',
    storageBucket: 'traffix-app-ac817.firebasestorage.app',
    iosBundleId: 'com.example.traffix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASfgrFkYB0fr1nT28fPEBJ3fD01Cxc8L0',
    appId: '1:796483662542:web:7134c3bad2f4f2ce35169f',
    messagingSenderId: '796483662542',
    projectId: 'traffix-app-ac817',
    authDomain: 'traffix-app-ac817.firebaseapp.com',
    storageBucket: 'traffix-app-ac817.firebasestorage.app',
    measurementId: 'G-W049CHXBM1',
  );
}
